# Auto-generated normalized binary glyph templates.
# Derived from user-provided replay captures. Raw replay screenshots are not stored here.
# Rank masks: 32x32 bits = 128 bytes. Suit masks: 28x28 bits = 98 bytes.

RANK_TEMPLATES_B64 = {
  "2": [
    "AAAAAAB//AAAf/wAAH/8AAH//wAB//8AB/gf4Af4H+AHgADwB4AA8AeAAPAHgADwB4AA8AeAAPAHgADwAAAD8AAAH+AAAB/gAAB/4AAAf+AAAH/gAAD/AAAA/wAAH/wAAB/8AAAf/AAAf4AAAf8AAAH/AAAB+AAAAfgAAAH4AAA="
  ],
  "3": [
    "AAAAAA///+AP///gD///4A///+AP///gDgAH4A4AB+AOAD+ADgA/gAAA/gAAAP4AAA/4AAAP+AAAD/gAAD//gAH//+AB///gAD4H+AA+B/gAPgf4AAAAeAAAAHgAAAB4AAAAeAAAAHgAAAAYAAAAGAAAABgAAAB4AAAAeAAAAHg="
  ],
  "4": [
    "AAAAAAAAHgAAAB4AAAAeAAAAfgAAAH4AAAB+AAAAfgAAAP4AAAD+AAAH/gAAB/4AAAf+AAAH/gAAH54AAB+eAAAfHgAAPx4AAD8eAAA/HgAB+B4AAfgeAAH4HgAH4B4AB+AeAAfgHgAH///wB///8Af///AAAB4AAAAeAAAAHgA="
  ],
  "5": [
    "AAAAAAP//gAD//4AA//+AAP//gAD//4AA8AAAAPAAAADwAAAA8AAAAPAAAADwAAAA8AAAAPAAAADwAAAA//4AAP//gAD//4AA/A/gAPwP4AD8D+AAgAH4AIAB+AAAAfgAAAH4AAAB+AAAAHgAAAB4AAAAeAAAAHgAAAB4AAAAeA="
  ],
  "6": [
    "AAAAAAAf/AAAH/wAAB/8AAB//+AAf//gAf8f8AH/H/AB+APwAfgD8AfgAOAH4ADgB+AAAAfgAAAH4AAAB+f8AAf//wAH//8AB/8f4Af/H+AH/x/gB/gD8Af4A/AH4ADwB+AA8AfgAPAH4ADwB+AA8AfgAPAH4ADwB+AA8AfgAPA="
  ],
  "7": [
    "AAAAAAf//4AH//+AB///gAf///AGAAPwBgAD8AYAA/AGAB+ABgAfgAAAH4AAAH4AAAB+AAAAfgAAAHwAAAB8AAAA/AAAAPwAAAD8AAAA/AAAB+AAAAfgAAAH4AAAH4AAAB+AAAAfgAAAH4AAAB+AAAAfgAAAPwAAAD8AAAA/AAA="
  ],
  "8": [
    "AAAAAAA/gAAAP4AAAD+AAAH//AAB4P4AAeD+AAHg/gABwH4AAcB+AAAAHgAAAB4AAAAeAAAAHgABwH4AAcB+AAHg/gAB//wAAf/8AAH//AAB//4AAf/+AAHAf4AAAB+AAAAfgAAAH4AAAAOAAAADgAAAA4AAAB+AAAAfgAAAH4A="
  ],
  "9": [
    "AAAAAAAfwAAAH8AAAB/AAAB//gAD8H8AA/B/AAPwfwAD4D8AA+A/AAPgB+ADgAfgA4AH4AOAB+ADgAHgA4AB4AOAB+AD4AfgA+AH4APgB+AD8D/gA/A/4AP//+AAf//gAH//4AB//+AAAAHgAAAB4AAAB+AAAAfgAAAH4AAAB+A="
  ],
  "A": [
    "AAAAAAAP+AAAD/gAAA/4AAAP+AAAD/gAAA/4AAAP+AAAH/gAAB/4AAAf/gAAH/4AAB/+AAAf/gAAH/4AAB/+AAAf/gAAfj8AAH4/AAB+PwAAfj8AAH4/AAB+PwAAfj8AAH4/AAB+PwAAf/8AAH//AAP//+AD8AfgA/AH4APwB+A="
  ],
  "K": [
    "AAAAAA/w//gP8P/4D/D/+A/w//gPwD8AD8A/AA/APwAPwP4AD8D+AA/A/gAPw/AAD8PwAA/D8AAPz8AAD8/AAA//wAAP/wAAD/8AAA//AAAP/8AAD//AAA/zwAAPw/AAD8PwAA/D8AAPwPAAD8DwAA/A/gAPwD4AD8A+AA/APgA="
  ],
  "Q": [
    "AAAAAAAH/AAAB/wAAAf8AAAf/gAAPx+AAD8fgAA/H4AAOAOAADgDgAA4A4AAOAOAADgDgAA4A4AAOAOAADgDgAA4A4AAOAOAADgDgAA4A4AAOAOAADgDgAH/A4AB/+OAAf/jgAH/44AB//+AAf//gAA4/4AAOH+AADh/gAA4f4A="
  ],
  "J": [
    "AAAAAAAB/+AAAf/gAAH/4AAB/+AAAf/gAAA+AAAAPgAAAD4AAAA+AAAAPgAAAD4AAAA+AAAAPgAAAD4AAAA+AAAAPgAAAD4AAAA+AAAAPgAAAD4AAAA+AAAAPgAAAD4AAAA+AAAAPgADwD4AA8A+AAPAPgADwD4AA8A+AAPAPgA="
  ],
  "T": [
    "AAAAAA4AP4AOAD+ADgA/gA4B//gOAf/4DgH5+A4B+fgOD8B4Dg/AeA4PABgODwAYDg8AGA4PABgODwAYDg8AGA4PABgODwAYDg8AGA4PABgODwAYDg8AGA4PABgODwAYDg8AGA4PABgODwAYDg8AGA4PABg="
  ]
}

SUIT_TEMPLATES_B64 = {
  "S": [
    "AAAAAAAgAAACAAAAIAAAD4AAA/4AAD/gAA//gAH//AAf/8AB//8AH//wB///AH//8A///4D///gP//+A///4D///gP//+A///4B///ABw5wAHDnAAA+AAAD4AAAPgAAA+AA="
  ],
  "H": [
    "AAAAAH4D8D/9/8P/3/w//f/H////f///9////3////f///9////3////f///9////z///8B///wH///Af//8B///AH//8AD/+AAH/wAAf/AAB/8AAB/AAAH8AAACAAAAIAA="
  ],
  "D": [
    "AAAAAADAAAAMAAAAwAAADAAAA+AAAD4AAA/gAAD/gAAP+AAB/+AAH/4AB//4AH//gAf//AB///AH//8Af//AB//8AB//gAH/+AAf/gAA/4AAD/gAAD4AAAPgAAA+AAAD4AA="
  ],
  "C": [
    "AAAAAAA4AAADgAAAOAAAP+AAA/+AAD/4AAP/gAA/4AAD/gAAP+AAA/4AAQ+EABD4QAf//wD///gP//+A///4D///gP//+A///4B///gBz5wAHPnAAA+AAAD4AAAPgAAA+AA="
  ]
}
