# Auto-generated normalized binary glyph templates.
# Derived from user-provided replay captures. Raw replay screenshots are not stored here.
# Glyphs are aligned to detected card rectangles so capture padding does not affect recognition.

RANK_TEMPLATES_B64 = {'A': ['AAAAAAAAAAAAAAAAAAAAAAAH8AAAB/AAAAfwAAAH8AAAD/AAAA/wAAAP+AAAD/gAAA/4AAAP+AAAD/gAAA/4AAA+PgAAPj4AAD4+AAA+PgAAPj4AAD4+AAA+PgAAP/4AAP//AAD//wAA+A8AAPgPAAD4DwAAAAAAAAAAAAAAAAA='],
 'K': ['AAAAAAAAAAAAAAAAAAAAAAf4/8AH+P/AB/j/wAHwPgAB8PgAAfD4AAHw+AAB8PgAAfHwAAH3wAAB98AAAf/AAAH/AAAB/wAAAf/AAAH/wAAB+cAAAfHwAAHx8AAB8PAAAfD4AAHw+AAB8DgAAfA4AAHwPgAAAAAAAAAAAAAAAAA='],
 'Q': ['AAAAAAAAAAAAAAAAAAAAAAAB+AAAB/4AAAf+AAAPDwAADgcAAA4HAAAOBwAADgcAAA4HAAAOBwAADgcAAA4HAAAOBwAADgcAAA4HAAAOBwAA/wcAAP/3AAD/9wAAP/8AAA7/AAAO/wAADj8AAA4/AAAPDwAAAAAAAAAAAAAAAAA='],
 'J': ['AAAAAAAAAAAAAAAAAAAAAAA/+AAAP/gAAD/4AAAHAAAABwAAAAcAAAAHAAAABwAAAAcAAAAHAAAABwAAAAcAAAAHAAAABwAAAAcAAAAHAAAABwAAAAcAAAAHAAAABwAAAAcAAAAHAAAABwAAAAcAAAAPAAAAAAAAAAAAAAAAAAA='],
 'T': ['AAAAAAAAAAAAAAAAAAAAAAcA+AAHB/8ABwf/AAcHzwAHDwfABw8HwAcOAcAHDgHABw4BwAcOAcAHDgHABw4BwAcOAcAHDgHABw4BwAcOAcAHDgHABw4BwAcOAcAHDgHABw4BwAcOAcAHDgHABw4BwAcPB8AAAAAAAAAAAAAAAAA='],
 '9': ['AAAAAAAAAAAAAAAAAAAAAAAP8AAAP/gAAD/4AAD4/gAB8D4AAfA+AAHwDwAB8A8AAcAPAAHADwABwA8AAcAPAAHwDwAB8A8AAPg/AAD4PwAA//8AAD//AAA//wAAAA8AAAAPAAAADwAAAA8AAAAPAAAAPgAAAAAAAAAAAAAAAAA=',
       'AAAAAAAAAAAAAAAAAAAAAAAPwAAAP/gAAD/4AAD4/gAB8D4AAfA+AAHwDwAB8A8AAcAPAAHABwABwAcAAcAPAAHwDwAB8A8AAPg/AAD4PwAA//8AAD//AAA//wAAAAcAAAAPAAAADwAAAA8AAAAPAAAAPgAAAAAAAAAAAAAAAAA='],
 '8': ['AAAAAAAAAAAAAAAAAAAAAAAH8AAAP/4AAD/+AAD+PwAA+A8AAPgPAADwBwAA8AcAAPAHAAD4DwAA+A8AAP4/AAA//gAAP/4AAP//AAD//wAB+A/AAfAHwAHwB8ABwAHAAcABwAHAAcAB8AfAAfAHwAD4DwAAAAAAAAAAAAAAAAA='],
 '7': ['AAAAAAAAAAAAAAAAAAAAAAH//wAB///AAf//wAHAB8ABwA8AAcAPAAAADwAAAA8AAAA+AAAAOAAAADgAAAD4AAAA+AAAAPgAAAHwAAAB8AAAAfAAAAfAAAAHwAAAB8AAAAfAAAAHwAAADwAAAA8AAAAPAAAAAAAAAAAAAAAAAAA='],
 '6': ['AAAAAAAAAAAAAAAAAAAAAAAP8AAAP/4AAD/+AAD+PwAA+A8AAPgPAAHwBgAB8AYAAfAAAAH38AAB9/AAAf/4AAH+PgAB/j4AAfgPAAH4DwAB8A8AAfAHAAHwBwAB8AcAAfAHAAHwBwAA+A8AAPgPAAD+PwAAAAAAAAAAAAAAAAA=',
       'AAAAAAAAAAAAAAAAAAAAAAAP8AAAP/4AAD/+AAD+PwAA+A8AAPgPAAHwBgAB8AYAAfAAAAH38AAB9/AAAf/4AAH+PgAB/j4AAfgPAAH4DwAB8AcAAfAHAAHwBwAB8AcAAfAHAAHwBwAA+A8AAPgPAAD4PgAAAAAAAAAAAAAAAAA='],
 '5': ['AAAAAAAAAAAAAAAAAAAAAAD/+AAA//gAAP/4AADwAAAA8AAAAPAAAADwAAAA8AAAAPAAAAD/8AAA//AAAP/4AAD4PgAA+D4AAMAPAADADwAAAA8AAAAHAAAABwAAAAcAAAAHAAAABwAAAA8AAAAPAAAAPgAAAAAAAAAAAAAAAAA=',
       'AAAAAAAAAAAAAAAAAAAAAAD/+AAA//gAAP/4AADwAAAA8AAAAPAAAADwAAAA8AAAAPAAAAD/8AAA//AAAP/4AAD4/gAA+P4AAMAPAADADwAAAA8AAAAHAAAABwAAAAcAAAAPAAAADwAAAA8AAAAPAAAAPgAAAAAAAAAAAAAAAAA='],
 '4': ['AAAAAAAAAAAAAAAAAAAAAAAAOAAAAPgAAAD4AAAA+AAAAfgAAAH4AAAH+AAAB/gAAAf4AAAPOAAADzgAAD44AAA+OAAAPjgAAPg4AAD4OAAA+DgAAfA4AAHwOAAB//8AAf//AAH//wAAADgAAAA4AAAAOAAAAAAAAAAAAAAAAAA=',
       'AAAAAAAAAAAAAAAAAAAAAAAAOAAAAPgAAAD4AAAA+AAAAfgAAAH4AAAH+AAAB/gAAAf4AAAPOAAADzgAAA44AAA+OAAAPjgAAPg4AAD4OAAA+DgAAfA4AAHwOAAB//8AAf//AAH//wAAADgAAAA4AAAAOAAAAAAAAAAAAAAAAAA='],
 '3': ['AAAAAAAAAAAAAAAAAAAAAAf//gAH//4AB//+AAcAPgAHAPgABwD4AAAB8AAAAfAAAA/AAAA/+AAAP/gAAP/+AAA4PwAAOD8AAAAHwAAAB8AAAAfAAAABwAAAAcAAAAHAAAAHwAAAB8AAAA8AAAAPAAAAPwAAAAAAAAAAAAAAAAA=',
       'AAAAAAAAAAAAAAAAAAAAAAf//gAH//4AB//+AAcAPgAHAPgABwD4AAAB8AAAAfAAAA/AAAA/+AAAP/gAAD/+AAA4PwAAOD8AAAAHwAAAB8AAAAfAAAABwAAAAcAAAAHAAAAHwAAAB8AAAAcAAAAHAAAAPwAAAAAAAAAAAAAAAAA=',
       'AAAAAAAAAAAAAAAAAAAAAAf//gAH//4AB//+AAcAPgAHAPgABwD4AAAB8AAAAfAAAA/AAAA/+AAAP/gAAP/+AAA4PwAAOD8AAAAHwAAAB8AAAAfAAAABwAAAAcAAAAHAAAAHwAAAB8AAAAcAAAAHAAAAPwAAAAAAAAAAAAAAAAA='],
 '2': ['AAAAAAAAAAAAAAAAAAAAAAA/8AAA//gAAP/4AAH4PgABwAcAAcAHAAHABwABwAcAAcAHAAAADwAAAA8AAAA+AAAA/gAAAP4AAAH4AAAB+AAAD/AAAD8AAAA/AAAAPgAAAPgAAAD4AAAB8AAAAfAAAAHAAAAAAAAAAAAAAAAAAAA=',
       'AAAAAAAAAAAAAAAAAAAAAAA/8AAA//gAAP/4AAH4PgABwAcAAcAHAAHABwABwAcAAcAHAAAADwAAAA8AAAA+AAAA/gAAAP4AAAH4AAAB+AAAD/AAAD8AAAA/AAAA/gAAAPgAAAD4AAAB8AAAAfAAAAHwAAAAAAAAAAAAAAAAAAA=',
       'AAAAAAAAAAAAAAAAAAAAAAA/8AAA//gAAP/4AAH4PgABwAcAAcAHAAHABwABwAcAAcAHAAAADwAAAA8AAAA+AAAA/gAAAP4AAAH4AAAB+AAAD/AAAD8AAAA/AAAA/gAAAPgAAAD4AAAB8AAAAfAAAAHAAAAAAAAAAAAAAAAAAAA=']}

SUIT_TEMPLATES_B64 = {'S': ['AAAAAAAAAAAAAAAAIAAAAgAAAPgAAB/AAAH8AAB/8AAP/4AA//gAD//gA//+AD//4Af//gB//+AH//4Af//gB//+AH//4AP//gAOO4AA47gAAPgAAA+AAAD4AAAAAAAAAAA='],
 'H': ['AAAAAAAAAAAAAAAAAAAB8HwAf9/wB/3/AP//8A///wD///AP//8A///wD///AP//8Af//wAf//AB//8AH//AAf/8AAf/AAA/4AAD/gAAD4AAAPgAAAIAAAAAAAAAAAAAAAA=',
       'AAAAAAAAAAAAAAAAAAAB8HwAf9/wB/3/AP//8A///wD///AP//8A///wD///AP//8Af//wB///AH//8AH//AAf/8AAf/AAA/4AAD/gAAD4AAAPgAAAIAAAAAAAAAAAAAAAA='],
 'D': ['AAAAAAAAAAAAAAAAIAAAAgAAACAAAA+AAAD4AAAfgAAB/AAAH8AAB/8AAP/4AA//gAP//gB//+AH//4AD//gAH/4AAf/gAB/8AAB/AAAH8AAAPgAAA+AAAD4AAAAAAAAAAA='],
 'C': ['AAAAAAAAAAAAAAAAOAAAA4AAAfwAAB/wAAH/AAAf8AAB/AAAH8AAAfwAAI+IAAj4gAP//gB//+AH//4Af//gB//+AH//4AP//gAO+4AA77gAAPgAAA+AAAD4AAAAAAAAAAA=',
       'AAAAAAAAAAAAAAAAOAAAA4AAAfwAAB/wAAH/AAAf8AAB/wAAH/AAAfwAAI+IAAj4gAP//gB//+AH//4Af//gB//+AH//4AP//gAO+4AA77gAAPgAAA+AAAD4AAAAAAAAAAA=']}
