# Auto-generated normalized binary glyph templates.
# Derived from user-provided replay captures. Raw replay screenshots are not stored here.

RANK_TEMPLATES_B64 = {
  "2": [
    "AAAAAAAAAAAAAAAAAAAAAAA/8AAA//gAAP/4AAH4PgABwAcAAcAHAAHABwABwAcAAcAHAAAADwAAAA8AAAA+AAAA/gAAAP4AAAH4AAAB+AAAD/AAAD8AAAA/AAAAPgAAAPgAAAD4AAAB8AAAAfAAAAHAAAAAAAAAAAAAAAAAAAA=",
    "AAAAAAAAAAAAAAAAAAAAAAA/+AAAP/gAAP/+AAD//gAD/B+AA/wfgAPAAeADwAHgA8AB4APAAeADwAHgA8AB4AAAB+AAAB+AAAAfgAAAf4AAAH+AAAD+AAAA/gAAD/gAAA/4AAA/gAAAP4AAAP8AAAD/AAAAAAAAAAAAAAAAAAA=",
    "AAAAAAAAAAAAAAAAAAAAAAA/8AAA//gAAP/4AAH4PgABwAcAAcAHAAHABwABwAcAAcAHAAAADwAAAA8AAAA+AAAA/gAAAP4AAAH4AAAB+AAAD/AAAD8AAAA/AAAA/gAAAPgAAAD4AAAB8AAAAfAAAAHwAAAAAAAAAAAAAAAAAAA=",
    "AAAAAAAAAAAAAAAAAAAAAAAf+AAAH/gAAH/8AAH8HwAB/B8AAeADwAHgA8AB4APAAeADwAHgA8AAAAfAAAAHwAAAHwAAAH8AAAB/AAAA/AAAAPwAAA/4AAAfgAAAH4AAAH8AAAB/AAAAfAAAAfAAAAHwAAAAAAAAAAAAAAAAAAA="
  ],
  "3": [
    "AAAAAAAAAAAAAAAAAAAAAAf//gAH//4AB//+AAcAPgAHAPgABwD4AAAB8AAAAfAAAA/AAAA/+AAAP/gAAP/+AAA4PwAAOD8AAAAHwAAAB8AAAAfAAAABwAAAAcAAAAHAAAAHwAAAB8AAAA8AAAAPAAAAPwAAAAAAAAAAAAAAAAA=",
    "AAAAAAAAAAAAAAAAAAAAAAH//gAB//4AAf/+AAEAPgABAPgAAQD4AAAB8AAAAfAAAA/AAAA/+AAAP/gAAP/+AAA4PwAAOD8AAAAHwAAAB8AAAAfAAAABwAAAAcAAAAHAAAAHwAAAB8AAAAcAAAAHAAAAPwAAAAAAAAAAAAAAAAA=",
    "AAAAAAAAAAAAAAAAAAAAAAf//gAH//4AB//+AAcAPgAHAPgABwD4AAAB8AAAAfAAAA/AAAA/+AAAP/gAAD/+AAA4PwAAOD8AAAAHwAAAB8AAAAfAAAABwAAAAcAAAAHAAAAHwAAAB8AAAAcAAAAHAAAAPwAAAAAAAAAAAAAAAAA=",
    "AAAAAAAAAAAAAAAAAAAAAAP//wAD//8AA///AAOAHwADgB8AA4B8AAOAfAAAAPgAAA/gAAAP4AAAH/wAAB/8AAAf/wAAHB/AABwfwAAAA+AAAAPgAAAD4AAAAOAAAADgAAAA4AAAAOAAAAPgAAADwAAAA8AAAAAAAAAAAAAAAAA=",
    "AAAAAAAAAAAAAAAAAAAAAAP//wAD//8AA///AAOAHwADgB8AA4B8AAOAfAAAAPgAAA/gAAAP4AAAH/wAAB/8AAB//wAAHB/AABwfwAAAA+AAAAPgAAAD4AAAAOAAAADgAAAA4AAAAOAAAAPgAAAHwAAAB8AAAAAAAAAAAAAAAAA="
  ],
  "4": [
    "AAAAAAAAAAAAAAAAAAAAAAAAOAAAAPgAAAD4AAAA+AAAAfgAAAH4AAAH+AAAB/gAAAf4AAAPOAAADzgAAD44AAA+OAAAPjgAAPg4AAD4OAAA+DgAAfA4AAHwOAAB//8AAf//AAH//wAAADgAAAA4AAAAOAAAAAAAAAAAAAAAAAA=",
    "AAAAAAAAAAAAAAAAAAAAAAAAOAAAAPgAAAD4AAAA+AAAAfgAAAH4AAAH+AAAB/gAAAf4AAAPOAAADzgAAD44AAA+OAAAPjgAAPg4AAD4OAAA+DgAAPA4AADwOAAA//8AAP//AAD//wAAADgAAAA4AAAAOAAAAAAAAAAAAAAAAAA=",
    "AAAAAAAAAAAAAAAAAAAAAAAAOAAAAPgAAAD4AAAA+AAAAfgAAAH4AAAH+AAAB/gAAAf4AAAPOAAADzgAAA44AAA+OAAAPjgAAPg4AAD4OAAA+DgAAfA4AAHwOAAB//8AAf//AAH//wAAADgAAAA4AAAAOAAAAAAAAAAAAAAAAAA=",
    "AAAAAAAAAAAAAAAAAAAAAAAAHgAAAB4AAAB+AAAAfgAAAH4AAAB+AAAA/gAAAP4AAAP+AAAD/gAAA/4AAAP+AAAPngAAPx4AAD8eAAA/HgAAPx4AAPweAAD8HgAA/B4AAPweAAPwHgAD8B4AA///4AP//+AAAAAAAAAAAAAAAAA=",
    "AAAAAAAAAAAAAAAAAAAAAAAAHAAAABwAAAB8AAAAfAAAAHwAAAD8AAAA/AAAA/wAAAP8AAAD/AAAD5wAAA+cAAAfHAAAHxwAAB8cAAB8HAAAfBwAAHwcAAHwHAAB8BwAAf//wAH//8AB///AAAAcAAAAHAAAAAAAAAAAAAAAAAA=",
    "AAAAAAAAAAAAAAAAAAAAAAAAHAAAABwAAAB8AAAAfAAAAHwAAAD8AAAA/AAAA/wAAAP8AAAD/AAAD5wAAA+cAAAPHAAAHxwAAB8cAAB8HAAAfBwAAHwcAAHwHAAB8BwAAf//wAH//8AB///AAAAcAAAAHAAAAAAAAAAAAAAAAAA="
  ],
  "5": [
    "AAAAAAAAAAAAAAAAAAAAAAP/+AAD//gAA//4AAP/+AADwAAAA8AAAAPAAAADwAAAA8AAAAPAAAADwAAAA8AAAAP/4AAD//gAA//4AAPw/gAD8P4AAwAfgAMAH4AAAB+AAAAfgAAAB4AAAAeAAAAHgAAAB4AAAAAAAAAAAAAAAAA=",
    "AAAAAAAAAAAAAAAAAAAAAAD/+AAA//gAAP/4AADwAAAA8AAAAPAAAADwAAAA8AAAAPAAAAD/8AAA//AAAP/4AAD4/gAA+P4AAMAPAADADwAAAA8AAAAHAAAABwAAAAcAAAAPAAAADwAAAA8AAAAPAAAAPgAAAAAAAAAAAAAAAAA=",
    "AAAAAAAAAAAAAAAAAAAAAAD/+AAA//gAAP/4AADwAAAA8AAAAPAAAADwAAAA8AAAAPAAAAD/8AAA//AAAP/4AAD4PgAA+D4AAMAPAADADwAAAA8AAAAHAAAABwAAAAcAAAAHAAAABwAAAA8AAAAPAAAAPgAAAAAAAAAAAAAAAAA=",
    "AAAAAAAAAAAAAAAAAAAAAAH/+AAB//gAAf/4AAHgAAAB4AAAAeAAAAHgAAAB4AAAAeAAAAHgAAAB/+AAAf/gAAH/+AAB8HwAAfB8AAGAHwABgB8AAAAfAAAABwAAAAcAAAAHAAAABwAAAAcAAAAfAAAAHwAAAAAAAAAAAAAAAAA="
  ],
  "6": [
    "AAAAAAAAAAAAAAAAAAAAAAAP+AAAD/gAAD//gAA//4AA/x/gAP8f4AD8B+AA/AfgA/ABgAPwAYAD8AAAA/AAAAPz+AAD//4AA//+AAP/H4AD/x+AA/wH4AP8B+AD8AHgA/AB4APwAeAD8AHgA/AB4APwAeAAAAAAAAAAAAAAAAA=",
    "AAAAAAAAAAAAAAAAAAAAAAAP8AAAP/4AAD/+AAD+PwAA+A8AAPgPAADwBgAA8AYAAPAAAAD38AAA9/AAAP/4AAD+PgAA/j4AAPgPAAD4DwAA8A8AAPAHAADwBwAA8AcAAPAHAADwBwAA+A8AAPgPAAD+PwAAAAAAAAAAAAAAAAA=",
    "AAAAAAAAAAAAAAAAAAAAAAAP8AAAP/4AAD/+AAD+PwAA+A8AAPgPAADwBgAA8AYAAPAAAAD38AAA9/AAAP/4AAD+PgAA/j4AAPgPAAD4DwAA8AcAAPAHAADwBwAA8AcAAPAHAADwBwAA+A8AAPgPAAD4PgAAAAAAAAAAAAAAAAA=",
    "AAAAAAAAAAAAAAAAAAAAAAAP+AAAD/gAAD//gAA//4AA/x/gAP8f4AD8B+AA/AfgA/ABgAPwAYAD8AAAA/AAAAPz+AAD//4AA//+AAP/H4AD/x+AA/wH4AP8B+AD8AfgA/AH4APwAeAD8AHgA/AB4APwAeAAAAAAAAAAAAAAAAA=",
    "AAAAAAAAAAAAAAAAAAAAAAAP+AAAD/gAAB//AAB/H8AAfx/AAHwHwAB8B8AB8AMAAfAAAAHwAAAB8/gAAfP4AAH//AAB/x8AAf8fAAH8B8AB/AfAAfADwAHwA8AB8APAAfADwAHwA8AB8APAAHwHwAB8B8AAAAAAAAAAAAAAAAA=",
    "AAAAAAAAAAAAAAAAAAAAAAAP+AAAD/gAAB//AAB/H8AAfx/AAHwHwAB8B8AB8AMAAfAAAAHwAAAB8/gAAfP4AAH//AAB/x8AAf8fAAH8B8AB/AfAAfAHwAHwA8AB8APAAfADwAHwA8AB8APAAHwHwAB8B8AAAAAAAAAAAAAAAAA="
  ],
  "7": [
    "AAAAAAAAAAAAAAAAAAAAAAH//wAB///AAf//wAHAB8ABwA8AAcAPAAAADwAAAA8AAAA+AAAAOAAAADgAAAD4AAAA+AAAAPgAAAHwAAAB8AAAAfAAAAfAAAAHwAAAB8AAAAfAAAAHwAAADwAAAA8AAAAPAAAAAAAAAAAAAAAAAAA="
  ],
  "8": [
    "AAAAAAAAAAAAAAAAAAAAAAAPwAAA//gAAP/4AAH4/gAB8D4AAfA+AAHADgABwA4AAcAOAAHwPgAB8D4AAfj+AAD/+AAA//gAAf/+AAH//gAB8D8AAcAPAAHADwABAAcAAQAHAAEABwABwA8AAcAPAAHwPgAAAAAAAAAAAAAAAAA="
  ],
  "9": [
    "AAAAAAAAAAAAAAAAAAAAAAAPwAAAP/gAAD/4AAD4/gAB8D4AAfA+AAHwDwAB8A8AAcAPAAHABwABwAcAAcAPAAHwDwAB8A8AAPg/AAD4PwAA//8AAD//AAA//wAAAAcAAAAPAAAADwAAAA8AAAAPAAAAPgAAAAAAAAAAAAAAAAA=",
    "AAAAAAAAAAAAAAAAAAAAAAAP8AAAP/gAAD/4AAD4/gAB8D4AAfA+AAHwDwAB8A8AAcAPAAHADwABwA8AAcAPAAHwDwAB8A8AAPg/AAD4PwAA//8AAD//AAA//wAAAA8AAAAPAAAADwAAAA8AAAAPAAAAPgAAAAAAAAAAAAAAAAA=",
    "AAAAAAAAAAAAAAAAAAAAAAAP+AAAD/gAAD/+AAA//gAA/H+AAPx/gAPwH4AD8B+AA/AH4APwB+ADwAfgA8AH4APAB+ADwAfgA8AH4APwB+AD8AfgAPwf4AD8H+AA///gAP//4AA//+AAP//gAAAH4AAAB+AAAAAAAAAAAAAAAAA=",
    "AAAAAAAAAAAAAAAAAAAAAAAP4AAAD+AAAD/+AAA//gAA/H+AAPx/gAPwH4AD8B+AA/AH4APwB+ADwAfgA8AH4APAAeADwAfgA8AH4APwB+AD8AfgAPwf4AD8H+AA///gAP//4AA//+AAP//gAAAB4AAAAeAAAAAAAAAAAAAAAAA="
  ],
  "A": [
    "AAAAAAAAAAAAAAAAAAAAAAAH8AAAB/AAAAfwAAAH8AAAD/AAAA/wAAAP+AAAD/gAAA/4AAAP+AAAD/gAAA/4AAA+PgAAPj4AAD4+AAA+PgAAPj4AAD4+AAA+PgAAP/4AAP//AAD//wAA+A8AAPgPAAD4DwAAAAAAAAAAAAAAAAA=",
    "AAAAAAAAAAAAAAAAAAAAAAAP4AAAD+AAAA/gAAAP4AAAD+AAAB/gAAAf4AAAH/gAAB/4AAAf+AAAH/gAAB/4AAAf+AAAfHwAAHx8AAB8fAAAfHwAAHx8AAB8fAAAfHwAAH/8AAB//AAB//8AAfAfAAHwHwAAAAAAAAAAAAAAAAA="
  ],
  "J": [
    "AAAAAAAAAAAAAAAAAAAAAAA//gAAP/4AAD/+AAA//gAAA4AAAAOAAAADgAAAA4AAAAOAAAADgAAAA4AAAAOAAAADgAAAA4AAAAOAAAADgAAAA4AAAAOAAAADgAAAA4AAAAOAAAADgAAAA4AAAAOAAAADgAAAAAAAAAAAAAAAAAA=",
    "AAAAAAAAAAAAAAAAAAAAAAAf/AAAH/wAAB/8AAADgAAAA4AAAAOAAAADgAAAA4AAAAOAAAADgAAAA4AAAAOAAAADgAAAA4AAAAOAAAADgAAAA4AAAAOAAAADgAAAA4AAAAOAAAADgAAAA4AAAAOAAAADgAAAAAAAAAAAAAAAAAA="
  ],
  "K": [
    "AAAAAAAAAAAAAAAAAAAAAAf4/8AH+P/AB/j/wAHwPgAB8PgAAfD4AAHw+AAB8PgAAfHwAAH3wAAB98AAAf/AAAH/AAAB/wAAAf/AAAH/wAAB+cAAAfHwAAHx8AAB8PAAAfD4AAHw+AAB8DgAAfA4AAHwPgAAAAAAAAAAAAAAAAA=",
    "AAAAAAAAAAAAAAAAAAAAAAH4/8AB+P/AAfj/wAHwPgAB8PgAAfD4AAHw+AAB8PgAAfHwAAH3wAAB98AAAf/AAAH/AAAB/wAAAf/AAAH/wAAB+cAAAfHwAAHx8AAB8PAAAfD4AAHw+AAB8DgAAfA4AAHwPgAAAAAAAAAAAAAAAAA=",
    "AAAAAAAAAAAAAAAAAAAAAA/8f/gP/H/4D/x/+A/8f/gD8B+AA/AfgAPwfgAD8H4AA/B+AAPwfgAD8PgAA/D4AAPz4AAD/+AAA//gAAP/gAAD/4AAA//gAAP/4AAD/OAAA/zgAAPw+AAD8PgAA/B4AAPweAAAAAAAAAAAAAAAAAA=",
    "AAAAAAAAAAAAAAAAAAAAAAP8f+AD/H/gA/x/4AHwHwAB8B8AAfB8AAHwfAAB8HwAAfD4AAHw+AAB8+AAAfPgAAH/4AAB/4AAAf+AAAH/4AAB/+AAAfzgAAHw+AAB8PgAAfB4AAHweAAB8HwAAfAcAAHwHAAAAAAAAAAAAAAAAAA="
  ],
  "Q": [
    "AAAAAAAAAAAAAAAAAAAAAAAB+AAAB/4AAAf+AAAPDwAADgcAAA4HAAAOBwAADgcAAA4HAAAOBwAADgcAAA4HAAAOBwAADgcAAA4HAAAOBwAA/wcAAP/3AAD/9wAAP/8AAA7/AAAO/wAADj8AAA4/AAAPDwAAAAAAAAAAAAAAAAA=",
    "AAAAAAAAAAAAAAAAAAAAAAAH8AAAD/gAAA/4AAA+PgAAOA4AADgOAAA4DgAAOA4AADgOAAA4DgAAOA4AADgOAAA4DgAAOA4AADgOAAA4DgAA/g4AAP/OAAD/zgAA//4AADn+AAA5/gAAOP4AADj+AAA+PgAAAAAAAAAAAAAAAAA=",
    "AAAAAAAAAAAAAAAAAAAAAAAD+AAAA/gAAA/+AAAP/gAAPx+AAD8fgAA8B4AAPAeAADwHgAA8B4AAPAeAADwHgAA8B4AAPAeAADwHgAA8B4AAPAeAADwHgAA8B4AD/weAA/8HgAP/54AD/+eAAP//gAD//4AAAAAAAAAAAAAAAAA=",
    "AAAAAAAAAAAAAAAAAAAAAAAD+AAAA/gAAA/8AAAfHwAAHx8AABwHAAAcBwAAHAcAABwHAAAcBwAAHAcAABwHAAAcBwAAHAcAABwHAAAcBwAAHAcAAf8HAAH/5wAB/+cAAH//AAB//wAAHP8AABx/AAAcfwAAAAAAAAAAAAAAAAA="
  ],
  "T": [
    "AAAAAAAAAAAAAAAAAAAAAAAD4AAAA+AAAD/+AAA//gAAP34AAD9+AAD8H4AA/B+AAPAHgADwB4AA8AeAAPAHgADwB4AA8AeAAPAHgADwB4AA8AeAAPAHgADwB4AA8AeAAPAHgADwB4AAAAAAAAAAAAAAAAA="
  ]
}

SUIT_TEMPLATES_B64 = {
  "C": [
    "AAAAAAAAAAAAAAAAHAAAAcAAAP8AAA/4AAD/gAAP+AAA/wAAD/AAAP8AAGPGAAY8YAD//gA//+AD//4AP//gA//+AD//4AD//gAHPOAAc84AADwAAAPAAAA8AAAAAAAAAAA=",
    "AAAAAAAAAAAAAAAAAAAAA8AAADwAAB/wAAH/gAAf+AAB/4AAH/gAAf+AAB/4AAH/AAGHxgAYfGAD//4AP//gD//+AP//4A///gD//+AP//4AP//gA//+AAAAAAAAAAAAAAA=",
    "AAAAAAAAAAAAAAAAOAAAA4AAAfwAAB/wAAH/AAAf8AAB/AAAH8AAAfwAAI+IAAj4gAP//gB//+AH//4Af//gB//+AH//4AP//gAO+4AA77gAAPgAAA+AAAD4AAAAAAAAAAA=",
    "AAAAAAAAAAAAAAAA4AAADgAAB/gAAH/AAAf8AAB/wAAH+AAAf4AAB/gAAx4wADHjAAP/+AA//+AD//4AP//gA//+AD//4AP//gA55wADnnAAAeAAAB4AAAHgAAAAAAAAAAA=",
    "AAAAAAAAAAAAAAAAAAAAA8AAADwAAB/wAAH/gAAf+AAB/4AAH/gAAf8AAB/wAAH/AAGHxgAYfGAD//4AP//gD//+AP//4A///gD//+AP//4AP//gA//+AAAAAAAAAAAAAAA=",
    "AAAAAAAAAAAAAAAA4AAADgAAB/gAAH/AAAf8AAB/wAAH/AAAf8AAB/gAAx4wADHjAAP/+AA//+AD//4AP//gA//+AD//4AP//gA55wADnnAAAeAAAB4AAAHgAAAAAAAAAAA=",
    "AAAAAAAAAAAAAAAAAAAAA8AAAf4AAB/gAAH/gAAf+AAB/4AAH+AAAf4AAB/gAAx8QAH//AAf/8AH//wAf//AB//8AH//wAf//AAf/8AA59wADn3AAAfAAAAAAAAAAAAAAAA=",
    "AAAAAAAAAAAAAAAAAAAAA8AAAf4AAB/gAAH/gAAf+AAB/4AAH/gAAf4AAB/gAAx8QAH//AAf/8AH//wAf//AB//8AH//wAf//AAf/8AA59wADn3AAAfAAAAAAAAAAAAAAAA="
  ],
  "D": [
    "AAAAAAAAAAAAAAAAwAAADAAAAMAAAB4AAAHgAAB+AAAH+AAAf4AAD/wAA//wAD//AAP/+AA//+AD//4AP/+AAP/wAA//AAD/wAAH+AAAf4AAAeAAAB4AAAHgAAAAAAAAAAA=",
    "AAAAAAAAAAAAAAAAIAAAAgAAACAAAA+AAAD4AAAfgAAB/AAAH8AAB/8AAP/4AA//gAP//gB//+AH//4AD//gAH/4AAf/gAB/8AAB/AAAH8AAAPgAAA+AAAD4AAAAAAAAAAA=",
    "AAAAAAAAAAAAAAAAAAAAAwAAADAAAAMAAAB8AAAHwAAB/AAAH8AAAf8AAB/wAAf/gAH//gAf/+AD//4AP//gD//+AP//4AH//gAH/+AAf/4AB/+AAH/4AAAAAAAAAAAAAAA=",
    "AAAAAAAAAAAAAAAAAAAAAwAAADAAAAMAAAB8AAAfwAAB/AAAH+AAA/+AAD/4AA//wAH//AAf/8AH//wAf//AAP/8AAP/wAA//AAD/4AAH+AAAf4AAAfAAAAAAAAAAAAAAAA="
  ],
  "H": [
    "AAAAAAAAAAAAAAAAAAAB8HwAf9/wB/3/AP//8A///wD///AP//8A///wD///AP//8Af//wAf//AB//8AH//AAf/8AAf/AAA/4AAD/gAAD4AAAPgAAAIAAAAAAAAAAAAAAAA=",
    "AAAAAAAAAAAAAAAAAAAHwfAAfz/AB/P8AH//8Af//wB///AH//8Af//wB///AH//8Af//AB//8AH//wAf/8AB//wAB/+AAB/gAAH+AAAPgAAA+AAAAwAAAAAAAAAAAAAAAA=",
    "AAAAAAAAAAAAAAAAAAAA/B+AD8H4A/5/gD/n+A///4D///gP//+A///4D///gP//+A///4A///gD//+AD//4AP//gA//+AD//4AD/+AAP/4AAAAAAAAAAAAAAAAAAAAAAAA=",
    "AAAAAAAAAAAAAAAAAAAAfB8AH+fwAf5/AH//8Af//wB///AH//8Af//wB///AH//8AH//wAH//AAf/8AB//wAH//AAP/wAAP8AAA/wAAA+AAAD4AAAGAAAAAAAAAAAAAAAA=",
    "AAAAAAAAAAAAAAAAAAAB+D4AH4PgA/z+AP//4A///gD//+AP//4A///gD//+AP//4AP//gA//+AB//4AH//gAf/+AB//4AB/+AAB/wAAH/AAAHwAAAfAAAAAAAAAAAAAAAA=",
    "AAAAAAAAAAAAAAAAAAAA/B+AD8H4A/5/gD/n+A///4D///gP//+A///4D///gP//+A///4A///gD//+AP//4A///gA//+AD//4AD/+AAP/4AAAAAAAAAAAAAAAAAAAAAAAA="
  ],
  "S": [
    "AAAAAAAAAAAAAAAAGAAAAYAAADwAAA/wAAD/AAAf+AAH/+AAf/4AB//gAP/+AA//4AP//gA//+AD//4AP//gA//+AD//4AD//gAHHOAAcc4AADwAAAPAAAA8AAAAAAAAAAA=",
    "AAAAAAAAAAAAAAAAIAAAAgAAAPgAAB/AAAH8AAB/8AAP/4AA//gAD//gA//+AD//4Af//gB//+AH//4Af//gB//+AH//4AP//gAOO4AA47gAAPgAAA+AAAD4AAAAAAAAAAA=",
    "AAAAAAAAAAAAAAAAwAAADAAAAeAAAH+AAAf4AAD/wAA//wAD//AAP/+AA//4AD//gAP//gA//+AD//4AP//gA//+AD//4AP/+AA45wADjnAAAeAAAB4AAAHgAAAAAAAAAAA=",
    "AAAAAAAAAAAAAAAAAAAAAwAAADAAAAfAAAH/AAAf8AAH/4AAf/gAH//gAf/+AB//4AP//gA//+AP//4A///gD//+AP//4A///gD//+AP//4AP//gA//+AAAAAAAAAAAAAAA=",
    "AAAAAAAAAAAAAAAAAAAAAwAAAHwAAAfAAAH+AAA/+AAD/4AA//wAD//AAP/8AB//wAf//AB//8AH//wAf//AB//8AH//wAf//AAf/8AA49wADj3AAAfAAAAAAAAAAAAAAAA="
  ]
}
